
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

linters:
  enable:
    - asasalint
    - asciicheck
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - exhaustive
    - exportloopref
    - gochecknoinits
    - gocheckcompilerdirectives
    - gocritic
    - gocyclo
    - gofumpt
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - loggercheck
    - mirror
    - makezero
    - megacheck
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - staticcheck
    - stylecheck
    - thelper
    - typecheck
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace
  fast: false
